import React, { createContext, useState, useContext, useEffect } from 'react';

const PreferencesContext = createContext();

export const usePreferences = () => useContext(PreferencesContext);

export const PreferencesProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [currency, setCurrency] = useState('PHP');
  const [theme, setTheme] = useState(localStorage.getItem('theme') || 'light');

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('theme', theme);
  }, [theme]);

  const availableCurrencies = [
    { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
    { code: 'THB', symbol: '฿', name: 'Thai Baht' },
    { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
    { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
    { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
    { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
    { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
    { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
    { code: 'USD', symbol: '$', name: 'US Dollar' },
    { code: 'EUR', symbol: '€', name: 'Euro' },
    { code: 'GBP', symbol: '£', name: 'British Pound' },
    { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
    { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
    { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
    { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
    { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
    { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal' },
    { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
    { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
    { code: 'COP', symbol: '$', name: 'Colombian Peso' }
  ];

  const availableLanguages = [
    { code: 'en', name: 'English', native: 'English' },
    { code: 'tl', name: 'Tagalog', native: 'Tagalog' },
    { code: 'th', name: 'Thai', native: 'ไทย' },
    { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
    { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
    { code: 'ja', name: 'Japanese', native: '日本語' },
    { code: 'zh', name: 'Chinese', native: '简体中文' },
    { code: 'ko', name: 'Korean', native: '한국어' },
    { code: 'es', name: 'Spanish', native: 'Español' },
    { code: 'fr', name: 'French', native: 'Français' },
    { code: 'pt', name: 'Portuguese', native: 'Português' },
    { code: 'ar', name: 'Arabic', native: 'العربية' }
  ];

  const exchangeRates = { 
    PHP: 1, 
    THB: 0.60, MYR: 0.076, IDR: 275.0, SGD: 0.024,
    JPY: 2.65, CNY: 0.13, KRW: 23.5, 
    USD: 0.018, EUR: 0.016, GBP: 0.014, CAD: 0.024, AUD: 0.027, CHF: 0.016,
    AED: 0.065, SAR: 0.066, QAR: 0.064,
    BRL: 0.089, ARS: 15.0, COP: 70.0 
  };

  const translations = {
    en: {
      nav_home: "Home",
      nav_dest: "Destinations",
      nav_tours: "Featured Tours",
      nav_gallery: "Gallery",
      nav_connect: "Connect",
      nav_book: "BOOK NOW",
      book_now: "Book Now",
      view_details: "View Details",
      select: "Select",
      per_person: "per person",
      total: "Total",
      confirm: "Confirm Booking",
      pop_dest: "Most Popular Destinations",
      top_pkg: "Top Packages That Fit You",
      calc_price: "CALCULATE TOTAL PRICE",
      hero_island: "Island Paradise",
      hero_adv: "Adventure Awaits",
      hero_trail: "Find Your Trail",
      dest_title: "Find Your Place",
      tours_title: "Tour Packages",
      gal_title: "Visual Journey",
      conn_title: "Let us Connect",
      price_summary: "Price Summary",
      contact_info: "Contact Information",
      contact_desc: "Our travel experts are ready to assist you. Reach out to us via email, phone, or visit our office.",
      head_office: "Head Office",
      phone: "Phone Number",
      email_addr: "Email Address",
      send_msg: "Send Us a Message",
      your_name: "Your Name",
      your_email: "Your Email",
      subject: "Subject",
      message: "Message",
      placeholder_help: "How can we help?",
      placeholder_msg: "Write your message here...",
      btn_send: "SEND MESSAGE",
      booking_title: "Secure Your Spot",
      booking_desc: "Complete your booking and pack your bags",
      trip_details: "Trip Details",
      dest_pkg: "Destination / Package",
      select_pkg: "-- Select a Package --",
      travel_date: "Travel Date",
      num_guests: "Number of Guests",
      adults: "Adults",
      adults_desc: "12+ years",
      children: "Children",
      children_desc: "50% Off (2-11 yrs)",
      infants: "Infants",
      infants_desc: "Free (Under 2 years old)",
      acc_class: "Accommodation Class",
      std_class: "Standard",
      std_desc: "Included",
      deluxe_class: "Deluxe",
      lux_class: "Luxury",
      pax: "/pax",
      lead_guest: "Lead Guest Details",
      full_name: "Full Name",
      carbon_footprint: "Carbon Footprint - Forest Foundation Philippines",
      carbon_desc: "Air travel and ground transport generate emissions. The estimated footprint for",
      carbon_desc2: "traveler(s) is",
      carbon_desc3: "Help us offset this by contributing to local Philippine reforestation projects.",
      offset_carbon: "Offset My Carbon Footprint",
      optional_addons: "Optional Add-ons",
      transfer: "Roundtrip Airport Transfer",
      transfer_desc: "Hassle-free pick up and drop off.",
      insurance: "Travel Insurance",
      insurance_desc: "Full coverage per guest.",
      dinner: "Romantic Dinner Setup",
      dinner_desc: "Candlelit dinner by the beach.",
      payment_details: "Payment Details",
      how_paying: "How are we paying?",
      split_1: "Just me (Pay in full)",
      split_ways: "Split",
      split_ways2: "ways",
      invoice_emails: "Email Addresses for Invoices:",
      lead_email: "Lead Booker's Email",
      friend_email: "Friend",
      friend_email2: "'s Email",
      each_pays: "Each person will pay",
      invoices_tied: "Invoices will be tied to the emails above.",
      payment_method: "Payment Method",
      select_summary: "Select a package to see summary",
      split: "Split",
      ways: "ways",
      per_person2: "/person",
      secure_payment: "Secure Encrypted Payment",
      processing: "Processing...",
      region: "Region",
      all_regions: "All Regions",
      accommodation: "Accommodation",
      all_acc: "All Accommodations",
      keyword_search: "Keyword Search",
      search_placeholder: "Type to search...",
      filters: "Filters",
      clear_all: "Clear All",
      explore_regions: "Explore Regions",
      major_regions: "6 Major Regions",
      view_acc: "View Accommodations",
      search_results: "Search Results",
      dest_found: "destination(s) found",
      no_match: "No matching accommodations",
      no_match_desc: "Try removing some of your active filters from the sidebar.",
      back_places: "← Back to All Places",
      pay_offers: "PAYMENT & OFFERS",
      facilities: "FACILITIES",
      details: "DETAILS",
      bed_type: "Bed Type",
      num_bedrooms: "Bedrooms",
      beach_access: "Beach Access",
      hiking: "Hiking",
      distance: "Distance",
      family: "Family",
      view_360: "360° VIEW",
      full_screen: "Full Screen",
      starting_at: "Starting at",
      per_night: "/ night",
      weather: "Weather",
      location: "Location",
      select_region_first: "Select a Region first",
      all_locations: "All Locations",
      explore_by_region: "Explore by Region",
      regions_count: "Regions",
      destinations: "Destinations",
      locations_count: "Locations",
      gallery: "Gallery",
      photos_count: "Photos",
      back_to_regions: "Back to All Regions",
      back_to: "Back to",
      promo_banner: "MONSOON SPECIAL: 30% OFF on all Palawan packages!",
      stats_clients: "SATISFIED CLIENTS",
      stats_tours: "TOURS ORGANIZED",
      stats_dest: "DESTINATIONS",
      
      // ⚡ NEW ISLAND HOPPING KEYS
      island_subtitle: "DISCOVERY",
      island_title: "The Island Hoppers",
      island_desc1: "Sometimes the best adventures begin where the ocean meets the shore. Step aboard a traditional bangka, feel the sea breeze, and hop between pristine islands waiting to be discovered.",
      island_desc2: "Navigate past towering limestone cliffs into hidden lagoons of crystal-clear turquoise water. Drop your anchor at secluded white-sand beaches and dive into vibrant marine sanctuaries.",
      island_btn: "Explore Island Tours",
      
      regional: "Regional",
      pop_dest_desc: "Discover the key regions and landmarks the Philippines has to offer.",
      view_all_dest: "View All Destinations",
      relaxation: "RELAXATION",
      bask_sun: "Bask Under the Sun",
      sun_desc1: "Feel the warmth of the tropical sun on your skin as you unwind on some of the world's most beautiful, powdery white sand beaches.",
      sun_desc2: "Let the gentle rhythm of the waves wash your worries away. Whether you are sipping a fresh coconut under a swaying palm tree or wading into crystal-clear turquoise waters, paradise is waiting.",
      book_beach: "Book a Beach Resort",
      packages: "Packages",
      explore_all_tours: "Explore All Tours",
      testimonials: "Testimonials",
      what_clients_say: "What Our Clients Say",
      quote1: "\"PhilGood Travels made our El Nido trip absolutely unforgettable! The team was professional and the experiences were beyond amazing.\"",
      quote2: "\"The Chocolate Hills tour was breathtaking! Everything was well-organized and our guide was incredibly knowledgeable.\"",
      quote3: "\"As a first-time visitor to the Philippines, I was impressed by the service and beautiful destinations. Highly recommend!\"",
      ready_adventure: "Ready for Your Next Adventure?",
      ready_desc: "Book your dream Philippine vacation today and create memories that will last a lifetime.",
      start_journey: "START YOUR JOURNEY",
      underwater: "UNDERWATER",
      next_dive: "Ready for Your Next Dive?",
      dive_desc1: "Descend into the deep blue. Discover vibrant coral reefs, swim alongside majestic sea turtles, and explore the mysteries of the ocean floor.",
      dive_desc2: "Beyond the technicolor gardens of coral lies a world frozen in time. Navigate through haunting shipwrecks and silent underwater caverns where history rests beneath the tides.",
      view_diving: "View Diving Packages"
    },
    es: {
      nav_home: "Inicio",
      nav_dest: "Destinos",
      nav_tours: "Tours Destacados",
      nav_gallery: "Galería",
      nav_connect: "Conectar",
      nav_book: "RESERVAR",
      book_now: "Reservar Ahora",
      view_details: "Ver Detalles",
      select: "Seleccionar",
      per_person: "por persona",
      total: "Total",
      confirm: "Confirmar Reserva",
      pop_dest: "Destinos Más Populares",
      top_pkg: "Los Mejores Paquetes",
      calc_price: "CALCULAR PRECIO TOTAL",
      hero_island: "PARAÍSO ISLEÑO",
      hero_adv: "LA AVENTURA ESPERA",
      hero_trail: "ENCUENTRA TU RUTA",
      dest_title: "ENCUENTRA TU LUGAR",
      tours_title: "PAQUETES TURÍSTICOS",
      gal_title: "VIAJE VISUAL",
      conn_title: "CONTÁCTANOS",
      price_summary: "Resumen de Precios",
      contact_info: "Información de Contacto",
      contact_desc: "Nuestros expertos en viajes están listos para ayudarle. Contáctenos por correo, teléfono o visite nuestra oficina.",
      head_office: "Sede Principal",
      phone: "Número de Teléfono",
      email_addr: "Correo Electrónico",
      send_msg: "Envíenos un Mensaje",
      your_name: "Su Nombre",
      your_email: "Su Correo",
      subject: "Asunto",
      message: "Mensaje",
      placeholder_help: "¿Cómo podemos ayudar?",
      placeholder_msg: "Escriba su mensaje aquí...",
      btn_send: "ENVIAR MENSAJE",
      booking_title: "Asegura tu lugar",
      booking_desc: "Completa tu reserva y haz las maletas",
      trip_details: "Detalles del viaje",
      dest_pkg: "Destino / Paquete",
      select_pkg: "-- Selecciona un paquete --",
      travel_date: "Fecha de viaje",
      num_guests: "Número de huéspedes",
      adults: "Adultos",
      adults_desc: "12+ años",
      children: "Niños",
      children_desc: "50% Dto (2-11 años)",
      infants: "Bebés",
      infants_desc: "Gratis (Menos de 2)",
      acc_class: "Clase de Alojamiento",
      std_class: "Estándar",
      std_desc: "Incluido",
      deluxe_class: "Deluxe",
      lux_class: "Lujo",
      pax: "/pax",
      lead_guest: "Detalles del huésped principal",
      full_name: "Nombre completo",
      carbon_footprint: "Huella de Carbono - ir a Forest Foundation Philippines",
      carbon_desc: "Los viajes generan emisiones. La huella estimada para",
      carbon_desc2: "viajero(s) es",
      carbon_desc3: "Ayúdanos a compensar esto contribuyendo a proyectos locales de reforestación.",
      offset_carbon: "Compensar mi huella",
      optional_addons: "Complementos Opcionales",
      transfer: "Traslado al aeropuerto",
      transfer_desc: "Recogida sin complicaciones.",
      insurance: "Seguro de viaje",
      insurance_desc: "Cobertura total.",
      dinner: "Cena Romántica",
      dinner_desc: "Cena a la luz de las velas.",
      payment_details: "Detalles de pago",
      how_paying: "¿Cómo pagaremos?",
      split_1: "Solo yo (Pago total)",
      split_ways: "Dividir en",
      split_ways2: "partes",
      invoice_emails: "Correos para facturas:",
      lead_email: "Correo del titular",
      friend_email: "Correo del amigo",
      friend_email2: "",
      each_pays: "Cada persona pagará",
      invoices_tied: "Las facturas se vincularán a estos correos.",
      payment_method: "Método de pago",
      select_summary: "Selecciona un paquete para ver el resumen",
      split: "Dividido en",
      ways: "partes",
      per_person2: "/persona",
      secure_payment: "Pago Seguro Encriptado",
      processing: "Procesando...",
      region: "Región",
      all_regions: "Todas las Regiones",
      accommodation: "Alojamiento",
      all_acc: "Todos los Alojamientos",
      keyword_search: "Búsqueda",
      search_placeholder: "Escribe para buscar...",
      filters: "Filtros",
      clear_all: "Borrar todo",
      explore_regions: "Explorar Regiones",
      major_regions: "6 Regiones Principales",
      view_acc: "Ver Alojamientos",
      search_results: "Resultados",
      dest_found: "destino(s) encontrado(s)",
      no_match: "No hay alojamientos",
      no_match_desc: "Intenta eliminar algunos filtros.",
      back_places: "← Volver a Todos los Lugares",
      pay_offers: "PAGO Y OFERTAS",
      facilities: "INSTALACIONES",
      details: "DETALLES",
      bed_type: "Tipo de Cama",
      num_bedrooms: "Dormitorios",
      beach_access: "Acceso a la playa",
      hiking: "Senderismo",
      distance: "Distancia",
      family: "Familia",
      view_360: "VISTA 360°",
      full_screen: "Pantalla Completa",
      starting_at: "Desde",
      per_night: "/ noche",
      weather: "Clima",
      location: "Ubicación",
      select_region_first: "Selecciona una región primero",
      all_locations: "Todas las ubicaciones",
      explore_by_region: "Explorar por Región",
      regions_count: "Regiones",
      destinations: "Destinos",
      locations_count: "Ubicaciones",
      gallery: "Galería",
      photos_count: "Fotos",
      back_to_regions: "Volver a Todas las Regiones",
      back_to: "Volver a",
      promo_banner: "OFERTA DE MONZÓN: ¡30% DE DESCUENTO en todos los paquetes a Palawan!",
      stats_clients: "CLIENTES SATISFECHOS",
      stats_tours: "TOURS ORGANIZADOS",
      stats_dest: "DESTINOS",
      
      // ⚡ SPANISH NEW KEYS
      island_subtitle: "DESCUBRIMIENTO",
      island_title: "Los Exploradores de Islas",
      island_desc1: "A veces, las mejores aventuras comienzan donde el océano se encuentra con la costa. Sube a bordo de una bangka tradicional, siente la brisa marina y salta entre islas vírgenes que esperan ser descubiertas.",
      island_desc2: "Navega más allá de imponentes acantilados de piedra caliza hacia lagunas escondidas de aguas turquesas cristalinas. Echa el ancla en playas solitarias de arena blanca y sumérgete en vibrantes santuarios marinos.",
      island_btn: "Explorar Tours por las Islas",
      
      regional: "Regional",
      pop_dest_desc: "Descubre las regiones y lugares clave que Filipinas tiene para ofrecer.",
      view_all_dest: "Ver Todos los Destinos",
      relaxation: "RELAJACIÓN",
      bask_sun: "Disfruta del Sol",
      sun_desc1: "Siente el calor del sol tropical en tu piel mientras te relajas en algunas de las playas de arena blanca más hermosas del mundo.",
      sun_desc2: "Deja que el suave ritmo de las olas lave tus preocupaciones. Ya sea bebiendo un coco fresco bajo una palmera o en aguas cristalinas, el paraíso te espera.",
      book_beach: "Reservar un Resort",
      packages: "Paquetes",
      explore_all_tours: "Explorar Todos los Tours",
      testimonials: "Testimonios",
      what_clients_say: "Lo que dicen nuestros clientes",
      quote1: "\"¡PhilGood Travels hizo que nuestro viaje a El Nido fuera inolvidable! El equipo fue profesional y las experiencias increíbles.\"",
      quote2: "\"¡El tour por las Colinas de Chocolate fue impresionante! Todo estuvo bien organizado y nuestro guía fue increíble.\"",
      quote3: "\"Como visitante por primera vez, quedé impresionado por el servicio. ¡Totalmente recomendado!\"",
      ready_adventure: "¿Listo para tu próxima aventura?",
      ready_desc: "Reserva las vacaciones de tus sueños hoy y crea recuerdos para toda la vida.",
      start_journey: "COMIENZA TU VIAJE",
      underwater: "SUBMARINO",
      next_dive: "¿Listo para tu próxima inmersión?",
      dive_desc1: "Desciende en el azul profundo. Descubre arrecifes de coral vibrantes, nada junto a tortugas marinas majestuosas y explora los misterios del fondo del océano.",
      dive_desc2: "Más allá de los jardines de coral de colores brillantes se encuentra un mundo congelado en el tiempo. Navega por naufragios y cavernas submarinas silenciosas.",
      view_diving: "Ver Paquetes de Buceo"
    },
    tl: {
      nav_home: "Bahay",
      nav_dest: "Destinasyon",
      nav_tours: "Sikat na Tours",
      nav_gallery: "Gallerio",
      nav_connect: "Kumonekta",
      nav_book: "MAG-BOOK NA",
      book_now: "Mag-book Na",
      view_details: "Tingnan ang Detalye",
      select: "Piliin",
      per_person: "bawat tao",
      total: "Kabuuan",
      confirm: "Kumpirmahin",
      pop_dest: "Mga Sikat na Destinasyon",
      top_pkg: "Mga Nangungunang Packages",
      calc_price: "KALKULAHIN ANG KABUUAN",
      hero_island: "PARAISO NG ISLA",
      hero_adv: "NAGHIHINTAY ANG ADVENTURE",
      hero_trail: "HANAPIN ANG IYONG LANDAS",
      dest_title: "HANAPIN ANG IYONG LUGAR",
      tours_title: "MGA TOUR PACKAGES",
      gal_title: "BISWAL NA PAGLALAKBAY",
      conn_title: "MAKIPAG-UGNAYAN",
      price_summary: "Buod ng Presyo",
      contact_info: "Impormasyon sa Pakikipag-ugnayan",
      contact_desc: "Handang tumulong ang aming mga eksperto sa paglalakbay. Makipag-ugnayan sa amin via email, telepono, o bisitahin ang aming opisina.",
      head_office: "Pangunahing Tanggapan",
      phone: "Numero ng Telepono",
      email_addr: "Email Address",
      send_msg: "Magpadala ng Mensahe",
      your_name: "Iyong Pangalan",
      your_email: "Iyong Email",
      subject: "Paksa",
      message: "Mensahe",
      placeholder_help: "Paano kami makakatulong?",
      placeholder_msg: "Isulat ang iyong mensahe rito...",
      btn_send: "IPADALA ANG MENSAHE",
      booking_title: "I-secure ang Iyong Pwesto",
      booking_desc: "Kumpletuhin ang iyong booking at mag-impake na",
      trip_details: "Detalye ng Biyahe",
      dest_pkg: "Destinasyon / Package",
      select_pkg: "-- Pumili ng Package --",
      travel_date: "Petsa ng Biyahe",
      num_guests: "Bilang ng Bisita",
      adults: "Matatanda",
      adults_desc: "12+ taon",
      children: "Bata",
      children_desc: "50% Off (2-11 taon)",
      infants: "Sanggol",
      infants_desc: "Libre (Pababa ng 2)",
      acc_class: "Uri ng Akomodasyon",
      std_class: "Standard",
      std_desc: "Kasama na",
      deluxe_class: "Deluxe",
      lux_class: "Luxury",
      pax: "/tao",
      lead_guest: "Detalye ng Pangunahing Bisita",
      full_name: "Buong Pangalan",
      carbon_footprint: "Carbon Footprint - Forest Foundation Philippines",
      carbon_desc: "Ang paglalakbay ay lumilikha ng emissions. Ang tinatayang footprint para sa",
      carbon_desc2: "na manlalakbay ay",
      carbon_desc3: "Tulungan kaming bawiin ito sa pamamagitan ng pagsuporta sa mga lokal na proyekto.",
      offset_carbon: "Bawiin ang Aking Carbon Footprint",
      optional_addons: "Mga Opsyonal na Add-on",
      transfer: "Hatid-Sundo sa Airport",
      transfer_desc: "Walang hassle na byahe.",
      insurance: "Travel Insurance",
      insurance_desc: "Buong saklaw bawat bisita.",
      dinner: "Romantic na Hapunan",
      dinner_desc: "Hapunan sa tabing-dagat.",
      payment_details: "Detalye ng Pagbabayad",
      how_paying: "Paano tayo magbabayad?",
      split_1: "Ako lang (Buong bayad)",
      split_ways: "Hatiin sa",
      split_ways2: "tao",
      invoice_emails: "Mga Email para sa Invoice:",
      lead_email: "Email ng Pangunahing Booker",
      friend_email: "Email ng Kaibigan",
      friend_email2: "",
      each_pays: "Ang bawat isa ay magbabayad ng",
      invoices_tied: "Ang mga invoice ay ipadadala sa mga email sa itaas.",
      payment_method: "Paraan ng Pagbabayad",
      select_summary: "Pumili ng package para makita ang buod",
      split: "Hati sa",
      ways: "tao",
      per_person2: "/tao",
      secure_payment: "Ligtas na Pagbabayad",
      processing: "Pinoproseso...",
      region: "Rehiyon",
      all_regions: "Lahat ng Rehiyon",
      accommodation: "Akomodasyon",
      all_acc: "Lahat ng Akomodasyon",
      keyword_search: "Paghahanap",
      search_placeholder: "Mag-type para maghanap...",
      filters: "Mga Filter",
      clear_all: "I-clear Lahat",
      explore_regions: "Tuklasin ang mga Rehiyon",
      major_regions: "6 Pangunahing Rehiyon",
      view_acc: "Tingnan ang Akomodasyon",
      search_results: "Resulta ng Paghahanap",
      dest_found: "nahanap na destinasyon",
      no_match: "Walang tugmang akomodasyon",
      no_match_desc: "Subukang alisin ang ilang filter sa gilid.",
      back_places: "← Bumalik sa Lahat ng Lugar",
      pay_offers: "PAGBABAYAD AT MGA ALOK",
      facilities: "MGA PASILIDAD",
      details: "DETALYE",
      bed_type: "Uri ng Kama",
      num_bedrooms: "Kwarto",
      beach_access: "Access sa Dagat",
      hiking: "Hiking",
      distance: "Distansya",
      family: "Pamilya",
      view_360: "360° NA TINGIN",
      full_screen: "Buong Screen",
      starting_at: "Nagsisimula sa",
      per_night: "/ gabi",
      weather: "Panahon",
      location: "Lokasyon",
      select_region_first: "Pumili muna ng Rehiyon",
      all_locations: "Lahat ng Lokasyon",
      explore_by_region: "Tuklasin bawat Rehiyon",
      regions_count: "Mga Rehiyon",
      destinations: "Mga Destinasyon",
      locations_count: "Mga Lokasyon",
      gallery: "Gallerio",
      photos_count: "Mga Litrato",
      back_to_regions: "Bumalik sa Lahat ng Rehiyon",
      back_to: "Bumalik sa",
      promo_banner: "MONSOON SPECIAL: 30% OFF sa lahat ng Palawan packages!",
      stats_clients: "MGA MASAYANG KLIENTE",
      stats_tours: "MGA TOUR NA ORGANISA",
      stats_dest: "MGA DESTINASYON",
      
      // ⚡ TAGALOG NEW KEYS
      island_subtitle: "PAGTUKLAS",
      island_title: "Ang Mga Island Hopper",
      island_desc1: "Minsan ang pinakamagandang pakikipagsapalaran ay nagsisimula kung saan nagtatagpo ang karagatan at dalampasigan. Sumakay sa tradisyonal na bangka, ramdamin ang simoy ng dagat, at mag-island hopping sa mga paraisong naghihintay matuklasan.",
      island_desc2: "Maglayag lampas sa matataas na limestone cliffs patungo sa mga nakatagong lagoon na may malinaw at turquoise na tubig. Ihulog ang angkla sa mga tagong white-sand beach at sumisid sa mga makulay na marine sanctuary.",
      island_btn: "Tuklasin ang Island Tours",
      
      regional: "Rehiyonal",
      pop_dest_desc: "Tuklasin ang mga pangunahing rehiyon at palatandaan sa Pilipinas.",
      view_all_dest: "Tingnan Lahat ng Destinasyon",
      relaxation: "PAGRE-RELAX",
      bask_sun: "Magbabad sa Araw",
      sun_desc1: "Ramdamin ang init ng tropikal na araw sa iyong balat habang nagrerelaks sa ilan sa pinakamagagandang white sand beaches sa mundo.",
      sun_desc2: "Hayaan ang banayad na alon na tangayin ang iyong mga alalahanin. Uminom ng sariwang buko o lumusong sa malinaw na tubig.",
      book_beach: "Mag-book ng Beach Resort",
      packages: "Mga Package",
      explore_all_tours: "Tuklasin Lahat ng Tour",
      testimonials: "Mga Testimonya",
      what_clients_say: "Ano ang Sabi ng Aming mga Kliente",
      quote1: "\"Ginawa ng PhilGood Travels na hindi makalimutan ang aming biyahe sa El Nido!\"",
      quote2: "\"Nakamamangha ang Chocolate Hills tour! Maayos ang lahat at napakagaling ng aming guide.\"",
      quote3: "\"Bilang first-time visitor sa Pilipinas, humanga ako sa serbisyo. Inirerekomenda ko ito!\"",
      ready_adventure: "Handa na para sa iyong susunod na adventure?",
      ready_desc: "I-book ang iyong pangarap na bakasyon sa Pilipinas ngayon at gumawa ng mga alaala.",
      start_journey: "SIMULAN ANG IYONG BIYAHE",
      underwater: "SA ILALIM NG DAGAT",
      next_dive: "Handa na sa susunod na dive?",
      dive_desc1: "Bumaba sa malalim na asul. Tuklasin ang makukulay na coral reefs at lumangoy kasama ng mga sea turtles.",
      dive_desc2: "Lagpas sa mga coral gardens ay isang mundong naka-freeze sa oras. Mag-navigate sa mga lumubog na barko at tahimik na mga kweba.",
      view_diving: "Tingnan ang Diving Packages"
    },
    fr: {
      nav_home: "Accueil",
      nav_dest: "Destinations",
      nav_tours: "Circuits",
      nav_gallery: "Galerie",
      nav_connect: "Contact",
      nav_book: "RÉSERVER",
      book_now: "Réserver",
      view_details: "Détails",
      select: "Sélectionner",
      per_person: "par personne",
      total: "Total",
      confirm: "Confirmer",
      pop_dest: "Destinations Populaires",
      top_pkg: "Meilleurs Forfaits",
      calc_price: "CALCULER LE PRIX",
      hero_island: "PARADIS INSULAIRE",
      hero_adv: "L'AVENTURE ATTEND",
      hero_trail: "TROUVEZ VOTRE VOIE",
      dest_title: "VOTRE PLACE",
      tours_title: "FORFAITS",
      gal_title: "VOYAGE VISUEL",
      conn_title: "CONTACTEZ-NOUS",
      price_summary: "Résumé des prix",
      contact_info: "Coordonnées",
      contact_desc: "Nos experts en voyages sont prêts à vous aider. Contactez-nous par e-mail, téléphone ou visitez notre bureau.",
      head_office: "Siège Social",
      phone: "Numéro de Téléphone",
      email_addr: "Adresse E-mail",
      send_msg: "Envoyez-nous un message",
      your_name: "Votre Nom",
      your_email: "Votre E-mail",
      subject: "Sujet",
      message: "Message",
      placeholder_help: "Comment pouvons-nous vous aider?",
      placeholder_msg: "Écrivez votre message ici...",
      btn_send: "ENVOYER LE MESSAGE",
      booking_title: "Sécurisez votre place",
      booking_desc: "Complétez votre réservation",
      trip_details: "Détails du voyage",
      dest_pkg: "Destination / Forfait",
      select_pkg: "-- Sélectionnez un forfait --",
      travel_date: "Date de voyage",
      num_guests: "Nombre d'invités",
      adults: "Adultes",
      adults_desc: "12+ ans",
      children: "Enfants",
      children_desc: "50% de réduc. (2-11 ans)",
      infants: "Bébés",
      infants_desc: "Gratuit (-2 ans)",
      acc_class: "Classe d'Hébergement",
      std_class: "Standard",
      std_desc: "Inclus",
      deluxe_class: "Deluxe",
      lux_class: "Luxe",
      pax: "/pers",
      lead_guest: "Détails de l'invité principal",
      full_name: "Nom complet",
      carbon_footprint: "Empreinte Carbone - aller à Forest Foundation Philippines",
      carbon_desc: "Les voyages génèrent des émissions. L'empreinte estimée pour",
      carbon_desc2: "voyageur(s) est de",
      carbon_desc3: "Aidez-nous à compenser cela.",
      offset_carbon: "Compenser mon empreinte",
      optional_addons: "Options supplémentaires",
      transfer: "Transfert aéroport",
      transfer_desc: "Prise en charge sans tracas.",
      insurance: "Assurance voyage",
      insurance_desc: "Couverture totale.",
      dinner: "Dîner Romantique",
      dinner_desc: "Dîner aux chandelles.",
      payment_details: "Détails de paiement",
      how_paying: "Comment payons-nous?",
      split_1: "Seulement moi (Paiement total)",
      split_ways: "Diviser en",
      split_ways2: "",
      invoice_emails: "E-mails pour les factures:",
      lead_email: "E-mail principal",
      friend_email: "E-mail de l'ami",
      friend_email2: "",
      each_pays: "Chaque personne paiera",
      invoices_tied: "Les factures seront liées à ces e-mails.",
      payment_method: "Mode de paiement",
      select_summary: "Sélectionnez un forfait pour voir le résumé",
      split: "Divisé par",
      ways: "",
      per_person2: "/pers",
      secure_payment: "Paiement Sécurisé",
      processing: "Traitement en cours...",
      region: "Région",
      all_regions: "Toutes les Régions",
      accommodation: "Hébergement",
      all_acc: "Tous les Hébergements",
      keyword_search: "Recherche",
      search_placeholder: "Taper pour rechercher...",
      filters: "Filtres",
      clear_all: "Tout effacer",
      explore_regions: "Explorer les Régions",
      major_regions: "6 Régions Principales",
      view_acc: "Voir les Hébergements",
      search_results: "Résultats de recherche",
      dest_found: "destination(s) trouvée(s)",
      no_match: "Aucun hébergement",
      no_match_desc: "Essayez de supprimer des filtres.",
      back_places: "← Retour à Tous les Lieux",
      pay_offers: "PAIEMENT ET OFFRES",
      facilities: "INSTALLATIONS",
      details: "DÉTAILS",
      bed_type: "Type de Lit",
      num_bedrooms: "Chambres",
      beach_access: "Accès à la plage",
      hiking: "Randonnée",
      distance: "Distance",
      family: "Famille",
      view_360: "VUE 360°",
      full_screen: "Plein Écran",
      starting_at: "À partir de",
      per_night: "/ nuit",
      weather: "Météo",
      location: "Lieu",
      select_region_first: "Sélectionnez d'abord une région",
      all_locations: "Tous les lieux",
      explore_by_region: "Explorer par région",
      regions_count: "Régions",
      destinations: "Destinations",
      locations_count: "Lieux",
      gallery: "Galerie",
      photos_count: "Photos",
      back_to_regions: "Retour à toutes les régions",
      back_to: "Retour à",
      promo_banner: "SPÉCIAL MOUSSON : -30% sur tous les forfaits Palawan !",
      stats_clients: "CLIENTS SATISFAITS",
      stats_tours: "CIRCUITS ORGANISÉS",
      stats_dest: "DESTINATIONS",
      
      // ⚡ FRENCH NEW KEYS
      island_subtitle: "DÉCOUVERTE",
      island_title: "Les Explorateurs d'Îles",
      island_desc1: "Parfois, les meilleures aventures commencent là où l'océan rencontre le rivage. Montez à bord d'une bangka traditionnelle, sentez la brise marine et naviguez d'île en île à la découverte de paradis préservés.",
      island_desc2: "Naviguez au-delà des imposantes falaises de calcaire vers des lagons cachés aux eaux turquoise cristallines. Jetez l'ancre sur des plages de sable blanc isolées et plongez dans des sanctuaires marins vibrants.",
      island_btn: "Explorer les circuits des îles",
      
      regional: "Régional",
      pop_dest_desc: "Découvrez les régions et sites incontournables des Philippines.",
      view_all_dest: "Voir toutes les destinations",
      relaxation: "DÉTENTE",
      bask_sun: "Prélassez-vous au soleil",
      sun_desc1: "Sentez la chaleur du soleil tropical sur votre peau pendant que vous vous détendez sur certaines des plus belles plages de sable blanc.",
      sun_desc2: "Laissez le doux rythme des vagues balayer vos soucis. Que vous sirotiez une noix de coco fraîche ou que vous pataugiez dans des eaux turquoises.",
      book_beach: "Réserver un complexe",
      packages: "Forfaits",
      explore_all_tours: "Explorer tous les circuits",
      testimonials: "Témoignages",
      what_clients_say: "Ce que disent nos clients",
      quote1: "\"PhilGood Travels a rendu notre voyage à El Nido absolument inoubliable !\"",
      quote2: "\"La visite des Chocolate Hills était à couper le souffle ! Tout était bien organisé.\"",
      quote3: "\"En tant que visiteur pour la première fois aux Philippines, j'ai été impressionné par le service. Je recommande vivement !\"",
      ready_adventure: "Prêt pour votre prochaine aventure ?",
      ready_desc: "Réservez vos vacances de rêve aux Philippines dès aujourd'hui et créez des souvenirs.",
      start_journey: "COMMENCEZ VOTRE VOYAGE",
      underwater: "SOUS-MARIN",
      next_dive: "Prêt pour votre prochaine plongée ?",
      dive_desc1: "Descendez dans le grand bleu. Découvrez des récifs coralliens vibrantes, nagez aux côtés de majestueuses tortues marines.",
      dive_desc2: "Au-delà des jardins de corail technicolor se trouve un monde figé dans le temps. Naviguez à travers des épaves obsédantes.",
      view_diving: "Voir les forfaits de plongée"
    },
    pt: {
      nav_home: "Início",
      nav_dest: "Destinos",
      nav_tours: "Tours Populares",
      nav_gallery: "Galeria",
      nav_connect: "Conectar",
      nav_book: "RESERVAR",
      book_now: "Reservar Agora",
      view_details: "Ver Detalhes",
      select: "Selecionar",
      per_person: "por pessoa",
      total: "Total",
      confirm: "Confirmar",
      pop_dest: "Destinos Populares",
      top_pkg: "Melhores Pacotes",
      calc_price: "CALCULAR PREÇO",
      hero_island: "PARAÍSO ILHÉU",
      hero_adv: "AVENTURA AGUARDA",
      hero_trail: "ENCONTRE SUA TRILHA",
      dest_title: "SEU LUGAR",
      tours_title: "PACOTES",
      gal_title: "JORNADA VISUAL",
      conn_title: "CONTATO",
      price_summary: "Resumo do Preço",
      contact_info: "Informações de Contato",
      contact_desc: "Nossos especialistas em viagens estão prontos para ajudar. Entre em contato por e-mail, telefone ou visite nosso escritório.",
      head_office: "Sede",
      phone: "Número de Telefone",
      email_addr: "Endereço de E-mail",
      send_msg: "Envie-nos uma Mensagem",
      your_name: "Seu Nome",
      your_email: "Seu E-mail",
      subject: "Assunto",
      message: "Mensagem",
      placeholder_help: "Como podemos ajudar?",
      placeholder_msg: "Escreva sua mensagem aqui...",
      btn_send: "ENVIAR MENSAGEM",
      booking_title: "Garanta seu lugar",
      booking_desc: "Conclua sua reserva",
      trip_details: "Detalhes da viagem",
      dest_pkg: "Destino / Pacote",
      select_pkg: "-- Selecione um pacote --",
      travel_date: "Data da viagem",
      num_guests: "Número de hóspedes",
      adults: "Adultos",
      adults_desc: "12+ anos",
      children: "Crianças",
      children_desc: "50% de desc. (2-11 anos)",
      infants: "Bebês",
      infants_desc: "Grátis (-2 anos)",
      acc_class: "Classe de Acomodação",
      std_class: "Padrão",
      std_desc: "Incluído",
      deluxe_class: "Deluxe",
      lux_class: "Luxo",
      pax: "/pax",
      lead_guest: "Detalhes do hóspede principal",
      full_name: "Nome completo",
      carbon_footprint: "Pegada de Carbono - ir para Forest Foundation Philippines",
      carbon_desc: "As viagens geram emissões. A pegada estimada para",
      carbon_desc2: "viajante(s) é de",
      carbon_desc3: "Ajude-nos a compensar isso.",
      offset_carbon: "Compensar minha pegada",
      optional_addons: "Complementos Opcionais",
      transfer: "Traslado ao aeroporto",
      transfer_desc: "Recolha sem problemas.",
      insurance: "Seguro de viagem",
      insurance_desc: "Cobertura total.",
      dinner: "Jantar Romântico",
      dinner_desc: "Jantar à luz de velas.",
      payment_details: "Detalhes de pagamento",
      how_paying: "Como vamos pagar?",
      split_1: "Só eu (Pagamento total)",
      split_ways: "Dividir em",
      split_ways2: "partes",
      invoice_emails: "E-mails para faturas:",
      lead_email: "E-mail principal",
      friend_email: "E-mail do amigo",
      friend_email2: "",
      each_pays: "Cada pessoa pagará",
      invoices_tied: "As faturas serão vinculadas a estes e-mails.",
      payment_method: "Método de pagamento",
      select_summary: "Selecione um pacote para ver o resumo",
      split: "Dividido por",
      ways: "",
      per_person2: "/pessoa",
      secure_payment: "Pagamento Seguro",
      processing: "Processando...",
      region: "Região",
      all_regions: "Todas as Regiões",
      accommodation: "Acomodação",
      all_acc: "Todas as Acomodações",
      keyword_search: "Pesquisa",
      search_placeholder: "Digite para pesquisar...",
      filters: "Filtros",
      clear_all: "Limpar tudo",
      explore_regions: "Explorar Regiões",
      major_regions: "6 Regiões Principales",
      view_acc: "Ver Acomodações",
      search_results: "Resultados da Pesquisa",
      dest_found: "destino(s) encontrado(s)",
      no_match: "Sem acomodações",
      no_match_desc: "Tente remover alguns filtros.",
      back_places: "← Voltar para Todos os Lugares",
      pay_offers: "PAGAMENTO E OFERTAS",
      facilities: "INSTALAÇÕES",
      details: "DETALHES",
      bed_type: "Tipo de Cama",
      num_bedrooms: "Quartos",
      beach_access: "Acesso à praia",
      hiking: "Caminhada",
      distance: "Distância",
      family: "Família",
      view_360: "VISTA 360°",
      full_screen: "Tela Cheia",
      starting_at: "A partir de",
      per_night: "/ noite",
      weather: "Clima",
      location: "Localização",
      select_region_first: "Selecione uma região primeiro",
      all_locations: "Todos os locais",
      explore_by_region: "Explorar por Região",
      regions_count: "Regiões",
      destinations: "Destinos",
      locations_count: "Locais",
      gallery: "Galeria",
      photos_count: "Fotos",
      back_to_regions: "Voltar para Todas as Regiões",
      back_to: "Voltar para",
      promo_banner: "OFERTA DE MONÇÕES: 30% DE DESCONTO em todos os pacotes para Palawan!",
      stats_clients: "CLIENTES SATISFEITOS",
      stats_tours: "TOURS ORGANIZADOS",
      stats_dest: "DESTINOS",
      
      // ⚡ PORTUGUESE NEW KEYS
      island_subtitle: "DESCOBERTA",
      island_title: "Os Exploradores de Ilhas",
      island_desc1: "Às vezes, as melhores aventuras começam onde o oceano encontra a costa. Suba a bordo de um bangka tradicional, sinta a brisa do mar e salte entre ilhas imaculadas à espera de serem descobertas.",
      island_desc2: "Navegue além de imponentes penhascos de calcário para lagoas escondidas de águas azul-turquesa cristalinas. Ancore em praias isoladas de areia branca e mergulhe em vibrantes santuários marinhos.",
      island_btn: "Explorar Passeios pelas Ilhas",
      
      regional: "Regional",
      pop_dest_desc: "Descubra as principais regiões e pontos turísticos que as Filipinas têm a oferecer.",
      view_all_dest: "Ver Todos os Destinos",
      relaxation: "RELAXAMENTO",
      bask_sun: "Aproveite o Sol",
      sun_desc1: "Sinta o calor do sol tropical em sua pele enquanto relaxa em algumas das mais belas praias de areia branca.",
      sun_desc2: "Deixe o ritmo suave das ondas levar suas preocupações. Quer você esteja bebendo um coco fresco ou nadando em águas cristalinas.",
      book_beach: "Reservar um Resort",
      packages: "Pacotes",
      explore_all_tours: "Explorar Todos os Tours",
      testimonials: "Depoimentos",
      what_clients_say: "O que nossos clientes dizem",
      quote1: "\"A PhilGood Travels tornou nossa viagem a El Nido absolutamente inesquecível!\"",
      quote2: "\"O tour pelas Colinas de Chocolate foi de tirar o fôlego! Tudo estava bem organizado.\"",
      quote3: "\"Como visitante de primeira viagem, fiquei impressionado com o serviço. Altamente recomendado!\"",
      ready_adventure: "Pronto para sua próxima aventura?",
      ready_desc: "Reserve as férias dos seus sonhos nas Filipinas hoje e crie memórias.",
      start_journey: "COMECE SUA JORNADA",
      underwater: "SUBAQUÁTICO",
      next_dive: "Pronto para o seu próximo mergulho?",
      dive_desc1: "Desça no azul profundo. Descubra recifes de corais vibrantes, nade ao lado de majestosas tartarugas marinhas.",
      dive_desc2: "Além dos jardins de corais encontra-se um mundo congelado no tempo. Navegue por naufragios assustadores.",
      view_diving: "Ver Pacotes de Mergulho"
    },
    ja: {
      nav_home: "ホーム",
      nav_dest: "目的地",
      nav_tours: "ツアー",
      nav_gallery: "ギャラリー",
      nav_connect: "連絡先",
      nav_book: "予約する",
      book_now: "今すぐ予約",
      view_details: "詳細を見る",
      select: "選択",
      per_person: "1人あたり",
      total: "合計",
      confirm: "予約を確定する",
      pop_dest: "人気の目的地",
      top_pkg: "おすすめパッケージ",
      calc_price: "合計料金",
      hero_island: "島の楽園",
      hero_adv: "冒険が待っている",
      hero_trail: "道を見つける",
      dest_title: "場所を見つける",
      tours_title: "パッケージ",
      gal_title: "ビジュアル",
      conn_title: "お問い合わせ",
      price_summary: "料金概要",
      contact_info: "連絡先情報",
      contact_desc: "旅行の専門家がお手伝いします。メール、電話、またはオフィスまでご連絡ください。",
      head_office: "本社",
      phone: "電話番号",
      email_addr: "メールアドレス",
      send_msg: "メッセージを送る",
      your_name: "お名前",
      your_email: "メール",
      subject: "件名",
      message: "メッセージ",
      placeholder_help: "どのようにお手伝いできますか？",
      placeholder_msg: "ここにメッセージを書いてください...",
      btn_send: "送信する",
      booking_title: "スポットを確保",
      booking_desc: "予約を完了してください",
      trip_details: "旅行の詳細",
      dest_pkg: "目的地/パッケージ",
      select_pkg: "-- パッケージを選択 --",
      travel_date: "旅行日",
      num_guests: "ゲスト数",
      adults: "大人",
      adults_desc: "12歳以上",
      children: "子供",
      children_desc: "50%オフ (2-11歳)",
      infants: "幼児",
      infants_desc: "無料 (2歳未満)",
      acc_class: "宿泊クラス",
      std_class: "標準",
      std_desc: "含まれています",
      deluxe_class: "デラックス",
      lux_class: "ラグジュアリー",
      pax: "/人",
      lead_guest: "代表者の詳細",
      full_name: "フルネーム",
      carbon_footprint: "カーボンフットプリント - Forest Foundation Philippinesへ",
      carbon_desc: "旅行は排出量を生み出します。推定フットプリント:",
      carbon_desc2: "旅行者あたり",
      carbon_desc3: "これを相殺するのに協力してください。",
      offset_carbon: "相殺する",
      optional_addons: "オプション",
      transfer: "空港送迎",
      transfer_desc: "手間のかからない送迎。",
      insurance: "旅行保険",
      insurance_desc: "完全な補償。",
      dinner: "ロマンチックなディナー",
      dinner_desc: "キャンドルライトディナー。",
      payment_details: "支払い詳細",
      how_paying: "支払い方法は？",
      split_1: "全額支払い",
      split_ways: "分割:",
      split_ways2: "人",
      invoice_emails: "請求書用メール:",
      lead_email: "代表者のメール",
      friend_email: "友人のメール",
      friend_email2: "",
      each_pays: "各人の支払い:",
      invoices_tied: "請求書はこれらのメールにリンクされます。",
      payment_method: "支払い方法",
      select_summary: "パッケージを選択して概要を表示",
      split: "分割",
      ways: "人",
      per_person2: "/人",
      secure_payment: "安全な支払い",
      processing: "処理中...",
      region: "地域",
      all_regions: "すべての地域",
      accommodation: "宿泊施設",
      all_acc: "すべての宿泊施設",
      keyword_search: "キーワード検索",
      search_placeholder: "検索する...",
      filters: "フィルター",
      clear_all: "すべてクリア",
      explore_regions: "地域を探索する",
      major_regions: "6つの主要地域",
      view_acc: "宿泊施設を見る",
      search_results: "検索結果",
      dest_found: "件の目的地が見つかりました",
      no_match: "一致する宿泊施設がありません",
      no_match_desc: "フィルターを解除してみてください。",
      back_places: "← すべての場所に戻る",
      pay_offers: "支払いとオファー",
      facilities: "設備",
      details: "詳細",
      bed_type: "ベッドタイプ",
      num_bedrooms: "ベッドルーム数",
      beach_access: "ビーチアクセス",
      hiking: "ハイキング",
      distance: "距離",
      family: "家族",
      view_360: "360°ビュー",
      full_screen: "全画面表示",
      starting_at: "最低価格",
      per_night: "/ 泊",
      weather: "天気",
      location: "場所",
      select_region_first: "最初に地域を選択してください",
      all_locations: "すべての場所",
      explore_by_region: "地域別に探索",
      regions_count: "地域",
      destinations: "目的地",
      locations_count: "場所",
      gallery: "ギャラリー",
      photos_count: "写真",
      back_to_regions: "すべての地域に戻る",
      back_to: "戻る",
      promo_banner: "モンスーンスペシャル：パラワンの全パッケージが30％オフ！",
      stats_clients: "満足したお客様",
      stats_tours: "企画されたツアー",
      stats_dest: "目的地",
      
      // ⚡ JAPANESE NEW KEYS
      island_subtitle: "発見",
      island_title: "アイランドホッパー",
      island_desc1: "最高の冒険は、海と岸が出会う場所から始まることがあります。伝統的なバンカ船に乗り込み、海風を感じながら、手つかずの島々を巡りましょう。",
      island_desc2: "そびえ立つ石灰岩の崖を通り抜け、透き通ったターコイズブルーの隠れたラグーンへ。人里離れた白砂のビーチにいかりを下ろし、活気ある海洋保護区に飛び込みましょう。",
      island_btn: "アイランドツアーを探索",
      
      regional: "地域",
      pop_dest_desc: "フィリピンが提供する主要な地域とランドマークを発見してください。",
      view_all_dest: "すべての目的地を見る",
      relaxation: "リラクゼーション",
      bask_sun: "太陽を浴びる",
      sun_desc1: "世界で最も美しい白砂のビーチでリラックスしながら、肌に熱帯の太陽の暖かさを感じてください。",
      sun_desc2: "波の穏やかなリズムで悩みを洗い流しましょう。ヤシの木の下で新鮮なココナッツを飲んだり、澄んだ海を歩いたり。",
      book_beach: "ビーチリゾートを予約する",
      packages: "パッケージ",
      explore_all_tours: "すべてのツアーを探索する",
      testimonials: "お客様の声",
      what_clients_say: "お客様の言葉",
      quote1: "「PhilGood Travelsはエルニドの旅行を絶対に忘れられないものにしてくれました！」",
      quote2: "「チョコレートヒルズのツアーは息をのむほどでした！すべてがよく組織されていました。」",
      quote3: "「初めての訪問者として、サービスに感銘を受けました。強くお勧めします！」",
      ready_adventure: "次の冒険の準備はできましたか？",
      ready_desc: "夢のフィリピン旅行を今すぐ予約して、一生の思い出を作りましょう。",
      start_journey: "旅を始める",
      underwater: "水中",
      next_dive: "次のダイビングの準備は？",
      dive_desc1: "深い青へ降下します。鮮やかなサンゴ礁を発見し、ウミガメと一緒に泳ぎましょう。",
      dive_desc2: "サンゴの庭園の向こうには時間が止まった世界があります。難破船や静かな洞窟をナビゲートします。",
      view_diving: "ダイビングパッケージを見る"
    },
    zh: {
      nav_home: "首页",
      nav_dest: "目的地",
      nav_tours: "特色行程",
      nav_gallery: "画廊",
      nav_connect: "联系我们",
      nav_book: "立即预订",
      book_now: "立即预订",
      view_details: "查看详情",
      select: "选择",
      per_person: "每人",
      total: "总计",
      confirm: "确认预订",
      pop_dest: "热门目的地",
      top_pkg: "热门套餐",
      calc_price: "计算总价",
      hero_island: "海岛天堂",
      hero_adv: "冒险在召唤",
      hero_trail: "寻找路线",
      dest_title: "寻找地点",
      tours_title: "旅游套餐",
      gal_title: "视觉之旅",
      conn_title: "联系我们",
      price_summary: "价格汇总",
      contact_info: "联系信息",
      contact_desc: "我们的旅行专家随时准备为您提供帮助。请通过电子邮件、电话或访问我们的办公室与我们联系。",
      head_office: "总部",
      phone: "电话号码",
      email_addr: "电子邮件地址",
      send_msg: "给我们发信息",
      your_name: "您的姓名",
      your_email: "您的邮箱",
      subject: "主题",
      message: "留言",
      placeholder_help: "我们能帮您什么？",
      placeholder_msg: "在此写下您的留言...",
      btn_send: "发送信息",
      booking_title: "确保您的位置",
      booking_desc: "完成您的预订",
      trip_details: "旅行详情",
      dest_pkg: "目的地/套餐",
      select_pkg: "-- 选择一个套餐 --",
      travel_date: "旅行日期",
      num_guests: "客人数",
      adults: "成人",
      adults_desc: "12岁+",
      children: "儿童",
      children_desc: "50%优惠 (2-11岁)",
      infants: "婴儿",
      infants_desc: "免费 (2岁以下)",
      acc_class: "住宿等级",
      std_class: "标准",
      std_desc: "包含",
      deluxe_class: "豪华",
      lux_class: "奢华",
      pax: "/人",
      lead_guest: "主要联系人详情",
      full_name: "全名",
      carbon_footprint: "碳足迹 - 访问 Forest Foundation Philippines",
      carbon_desc: "旅行会产生排放。预计碳足迹:",
      carbon_desc2: "旅客是",
      carbon_desc3: "请帮助我们抵消它。",
      offset_carbon: "抵消我的碳足迹",
      optional_addons: "可选附加项",
      transfer: "机场接送",
      transfer_desc: "无忧接送。",
      insurance: "旅行保险",
      insurance_desc: "全面保障。",
      dinner: "浪漫晚餐",
      dinner_desc: "海滩烛光晚餐。",
      payment_details: "付款详情",
      how_paying: "我们如何付款？",
      split_1: "只有我（全额付款）",
      split_ways: "平分给",
      split_ways2: "人",
      invoice_emails: "发票邮箱：",
      lead_email: "主要预订人邮箱",
      friend_email: "朋友的邮箱",
      friend_email2: "",
      each_pays: "每人将支付",
      invoices_tied: "发票将与上述邮箱绑定。",
      payment_method: "付款方式",
      select_summary: "选择套餐以查看摘要",
      split: "平分给",
      ways: "人",
      per_person2: "/人",
      secure_payment: "安全加密付款",
      processing: "处理中...",
      region: "地区",
      all_regions: "所有地区",
      accommodation: "住宿",
      all_acc: "所有住宿",
      keyword_search: "关键字搜索",
      search_placeholder: "输入以搜索...",
      filters: "筛选",
      clear_all: "全部清除",
      explore_regions: "探索地区",
      major_regions: "6大主要地区",
      view_acc: "查看住宿",
      search_results: "搜索结果",
      dest_found: "个目的地找到",
      no_match: "没有符合的住宿",
      no_match_desc: "请尝试移除一些筛选条件。",
      back_places: "← 返回所有地点",
      pay_offers: "付款与优惠",
      facilities: "设施",
      details: "详情",
      bed_type: "床型",
      num_bedrooms: "卧室数量",
      beach_access: "海滩通道",
      hiking: "徒步旅行",
      distance: "距离",
      family: "家庭",
      view_360: "360° 全景",
      full_screen: "全屏",
      starting_at: "起价",
      per_night: "/ 晚",
      weather: "天气",
      location: "位置",
      select_region_first: "请先选择一个地区",
      all_locations: "所有位置",
      explore_by_region: "按地区探索",
      regions_count: "个地区",
      destinations: "目的地",
      locations_count: "个位置",
      gallery: "画廊",
      photos_count: "张照片",
      back_to_regions: "返回所有地区",
      back_to: "返回",
      promo_banner: "季风特惠：所有巴拉望套餐享受30％的折扣！",
      stats_clients: "满意的客户",
      stats_tours: "组织的旅行",
      stats_dest: "目的地",
      
      // ⚡ CHINESE NEW KEYS
      island_subtitle: "发现",
      island_title: "跳岛探险家",
      island_desc1: "有时最好的冒险始于海洋与海岸相遇的地方。登上传统的螃蟹船（bangka），感受海风，在等待被发现的原始岛屿之间穿梭。",
      island_desc2: "驶过高耸的石灰岩悬崖，进入拥有清澈绿松石色海水的隐藏泻湖。在僻静的白沙滩抛锚，潜入充满活力的海洋保护区。",
      island_btn: "探索跳岛游",
      
      regional: "区域",
      pop_dest_desc: "发现菲律宾提供的主要地区和地标。",
      view_all_dest: "查看所有目的地",
      relaxation: "放松",
      bask_sun: "在阳光下沐浴",
      sun_desc1: "在世界上最美丽的白沙滩上放松时，感受热带阳光在皮肤上的温暖。",
      sun_desc2: "让海浪轻柔的节奏冲走你的烦恼。无论你是在棕榈树下喝着新鲜的椰子，还是在清澈的海水中涉水。",
      book_beach: "预订海滩度假村",
      packages: "套餐",
      explore_all_tours: "探索所有行程",
      testimonials: "客户评价",
      what_clients_say: "我们的客户怎么说",
      quote1: "\"PhilGood Travels让我们的爱妮岛之旅绝对难忘！\"",
      quote2: "\"巧克力山之旅令人叹为观止！一切都安排得很好。\"",
      quote3: "\"作为第一次来菲律宾的游客，我对这里的服务印象深刻。强烈推荐！\"",
      ready_adventure: "准备好迎接下一次冒险了吗？",
      ready_desc: "今天预订你梦想中的菲律宾假期，创造一生难忘的回忆。",
      start_journey: "开始你的旅程",
      underwater: "水下",
      next_dive: "准备好下一次潜水了吗？",
      dive_desc1: "潜入深蓝。发现生机勃勃的珊瑚礁，与雄伟的海龟一起游泳。",
      dive_desc2: "在彩色珊瑚花园之外，是一个被时间冻结的世界。穿行于沉船和寂静的水下洞穴中。",
      view_diving: "查看潜水套餐"
    },
    ar: {
      nav_home: "الرئيسية",
      nav_dest: "الوجهات",
      nav_tours: "جولات",
      nav_gallery: "المعرض",
      nav_connect: "تواصل",
      nav_book: "احجز الآن",
      book_now: "احجز الآن",
      view_details: "عرض التفاصيل",
      select: "اختر",
      per_person: "للشخص الواحد",
      total: "المجموع",
      confirm: "تأكيد الحجز",
      pop_dest: "الوجهات الشعبية",
      top_pkg: "أفضل الباقات",
      calc_price: "السعر الإجمالي",
      hero_island: "جنة الجزيرة",
      hero_adv: "المغامرة تنتظر",
      hero_trail: "اكتشف مسارك",
      dest_title: "وجهتك",
      tours_title: "باقات الجولات",
      gal_title: "رحلة بصرية",
      conn_title: "تواصل معنا",
      price_summary: "ملخص السعر",
      contact_info: "معلومات الاتصال",
      contact_desc: "خبراء السفر لدينا مستعدون لمساعدتك. تواصل معنا عبر البريد الإلكتروني أو الهاتف أو قم بزيارة مكتبنا.",
      head_office: "المكتب الرئيسي",
      phone: "رقم الهاتف",
      email_addr: "البريد الإلكتروني",
      send_msg: "أرسل لنا رسالة",
      your_name: "اسمك",
      your_email: "بريدك الإلكتروني",
      subject: "الموضوع",
      message: "الرسالة",
      placeholder_help: "كيف يمكننا المساعدة؟",
      placeholder_msg: "اكتب رسالتك هنا...",
      btn_send: "إرسال الرسالة",
      booking_title: "احجز مكانك",
      booking_desc: "أكمل حجزك",
      trip_details: "تفاصيل الرحلة",
      dest_pkg: "الوجهة / الباقة",
      select_pkg: "-- اختر باقة --",
      travel_date: "تاريخ السفر",
      num_guests: "عدد الضيوف",
      adults: "بالغين",
      adults_desc: "12+ سنة",
      children: "أطفال",
      children_desc: "خصم 50% (2-11 سنة)",
      infants: "رُضّع",
      infants_desc: "مجاناً (أقل من 2)",
      acc_class: "فئة الإقامة",
      std_class: "قياسي",
      std_desc: "مشمول",
      deluxe_class: "ديلوكس",
      lux_class: "فاخر",
      pax: "/شخص",
      lead_guest: "تفاصيل الضيف الرئيسي",
      full_name: "الاسم الكامل",
      carbon_footprint: "البصمة الكربونية - اذهب إلى Forest Foundation Philippines",
      carbon_desc: "السفر يولد انبعاثات. البصمة المقدرة هي:",
      carbon_desc2: "مسافر",
      carbon_desc3: "ساعدنا في تعويض ذلك.",
      offset_carbon: "تعويض بصمتي الكربونية",
      optional_addons: "إضافات اختيارية",
      transfer: "نقل المطار",
      transfer_desc: "استقبال وتوديع مريح.",
      insurance: "تأمين السفر",
      insurance_desc: "تغطية كاملة.",
      dinner: "عشاء رومانسي",
      dinner_desc: "عشاء على ضوء الشموع.",
      payment_details: "تفاصيل الدفع",
      how_paying: "كيف سندفع؟",
      split_1: "أنا فقط (دفع كامل)",
      split_ways: "تقسيم على",
      split_ways2: "أشخاص",
      invoice_emails: "رسائل البريد للفواتير:",
      lead_email: "البريد الرئيسي",
      friend_email: "بريد الصديق",
      friend_email2: "",
      each_pays: "سيدفع كل شخص",
      invoices_tied: "سيتم ربط الفواتير بهذه العناوين.",
      payment_method: "طريقة الدفع",
      select_summary: "اختر باقة لرؤية الملخص",
      split: "تقسيم",
      ways: "أشخاص",
      per_person2: "/شخص",
      secure_payment: "دفع آمن",
      processing: "جاري المعالجة...",
      region: "المنطقة",
      all_regions: "جميع المناطق",
      accommodation: "الإقامة",
      all_acc: "جميع أماكن الإقامة",
      keyword_search: "البحث بكلمة رئيسية",
      search_placeholder: "اكتب للبحث...",
      filters: "الفلاتر",
      clear_all: "مسح الكل",
      explore_regions: "استكشاف المناطق",
      major_regions: "6 مناطق رئيسية",
      view_acc: "عرض أماكن الإقامة",
      search_results: "نتائج البحث",
      dest_found: "وجهة وجدت",
      no_match: "لا توجد أماكن إقامة مطابقة",
      no_match_desc: "حاول إزالة بعض الفلاتر.",
      back_places: "← العودة إلى جميع الأماكن",
      pay_offers: "الدفع والعروض",
      facilities: "المرافق",
      details: "التفاصيل",
      bed_type: "نوع السرير",
      num_bedrooms: "غرف النوم",
      beach_access: "الوصول إلى الشاطئ",
      hiking: "المشي لمسافات طويلة",
      distance: "المسافة",
      family: "عائلة",
      view_360: "عرض 360 درجة",
      full_screen: "ملء الشاشة",
      starting_at: "يبدأ من",
      per_night: "/ ليلة",
      weather: "الطقس",
      location: "الموقع",
      select_region_first: "حدد منطقة أولاً",
      all_locations: "جميع المواقع",
      explore_by_region: "استكشف حسب المنطقة",
      regions_count: "مناطق",
      destinations: "وجهات",
      locations_count: "مواقع",
      gallery: "معرض",
      photos_count: "صور",
      back_to_regions: "العودة إلى جميع المناطق",
      back_to: "العودة إلى",
      promo_banner: "عرض الرياح الموسمية: خصم 30٪ على جميع باقات بالاوان!",
      stats_clients: "عملاء راضون",
      stats_tours: "جولات منظمة",
      stats_dest: "وجهات",
      
      // ⚡ ARABIC NEW KEYS
      island_subtitle: "اكتشاف",
      island_title: "مستكشفو الجزر",
      island_desc1: "أحيانًا تبدأ أفضل المغامرات حيث يلتقي المحيط بالشاطئ. اصعد على متن قارب البانغكا التقليدي، واشعر بنسيم البحر، وتنقل بين الجزر البكر التي تنتظر من يكتشفها.",
      island_desc2: "أبحر متجاوزًا منحدرات الحجر الجيري الشاهقة إلى البحيرات المخفية ذات المياه الفيروزية الصافية. ألقِ مرساتك في الشواطئ الرملية البيضاء المنعزلة واغطس في المحميات البحرية النابضة بالحياة.",
      island_btn: "استكشاف جولات الجزر",
      
      regional: "إقليمي",
      pop_dest_desc: "اكتشف المناطق والمعالم الرئيسية التي تقدمها الفلبين.",
      view_all_dest: "عرض جميع الوجهات",
      relaxation: "استرخاء",
      bask_sun: "استمتع تحت أشعة الشمس",
      sun_desc1: "اشعر بدفء الشمس الاستوائية على بشرتك بينما تسترخي على بعض من أجمل شواطئ الرمال البيضاء في العالم.",
      sun_desc2: "دع إيقاع الأمواج اللطيف يغسل همومك. سواء كنت تشرب جوز هند طازجًا تحت شجرة نخيل أو تخوض في مياه صافية.",
      book_beach: "احجز منتجع شاطئي",
      packages: "باقات",
      explore_all_tours: "استكشاف جميع الجولات",
      testimonials: "الشهادات",
      what_clients_say: "ماذا يقول عملاؤنا",
      quote1: "\"جعلت PhilGood Travels رحلتنا إلى إل نيدو لا تُنسى تمامًا!\"",
      quote2: "\"كانت جولة تلال الشوكولاتة تخطف الأنفاس! كان كل شيء منظمًا جيدًا.\"",
      quote3: "\"كزائر لأول مرة، أعجبت بالخدمة. أوصي بشدة!\"",
      ready_adventure: "مستعد لمغامرتك القادمة؟",
      ready_desc: "احجز إجازة أحلامك في الفلبين اليوم واصنع ذكريات.",
      start_journey: "ابدأ رحلتك",
      underwater: "تحت الماء",
      next_dive: "مستعد لغوصتك القادمة؟",
      dive_desc1: "انزل إلى اللون الأزرق العميق. اكتشف الشعاب المرجانية النابضة بالحياة واسبح بجانب السلاحف البحرية.",
      dive_desc2: "وراء حدائق المرجان يكمن عالم متجمد في الزمن. تنقل عبر حطام السفن والكهوف الهادئة.",
      view_diving: "عرض باقات الغوص"
    },
    th: {
      nav_home: "หน้าแรก",
      nav_dest: "จุดหมายปลายทาง",
      nav_tours: "ทัวร์แนะนำ",
      nav_gallery: "แกลเลอรี",
      nav_connect: "ติดต่อเรา",
      nav_book: "จองเลย",
      book_now: "จองเลย",
      view_details: "ดูรายละเอียด",
      select: "เลือก",
      per_person: "ต่อท่าน",
      total: "รวม",
      confirm: "ยืนยันการจอง",
      pop_dest: "จุดหมายปลายทางยอดนิยม",
      top_pkg: "แพ็คเกจยอดนิยม",
      calc_price: "คำนวณราคารวม",
      hero_island: "เกาะสวรรค์",
      hero_adv: "การผจญภัยรออยู่",
      hero_trail: "ค้นหาเส้นทางของคุณ",
      dest_title: "ค้นหาสถานที่ของคุณ",
      tours_title: "แพ็คเกจทัวร์",
      gal_title: "การเดินทางด้วยภาพ",
      conn_title: "ติดต่อเรา",
      price_summary: "สรุปราคา",
      contact_info: "ข้อมูลการติดต่อ",
      contact_desc: "ผู้เชี่ยวชาญด้านการเดินทางของเราพร้อมที่จะช่วยเหลือคุณ ติดต่อเราผ่านทางอีเมล โทรศัพท์ หรือเยี่ยมชมสำนักงานของเรา",
      head_office: "สำนักงานใหญ่",
      phone: "หมายเลขโทรศัพท์",
      email_addr: "ที่อยู่อีเมล",
      send_msg: "ส่งข้อความถึงเรา",
      your_name: "ชื่อของคุณ",
      your_email: "อีเมลของคุณ",
      subject: "หัวข้อ",
      message: "ข้อความ",
      placeholder_help: "เราจะช่วยคุณได้อย่างไร?",
      placeholder_msg: "เขียนข้อความของคุณที่นี่...",
      btn_send: "ส่งข้อความ",
      booking_title: "ยืนยันสถานที่ของคุณ",
      booking_desc: "ดำเนินการจองให้เสร็จสิ้น",
      trip_details: "รายละเอียดการเดินทาง",
      dest_pkg: "จุดหมายปลายทาง / แพ็คเกจ",
      select_pkg: "-- เลือกแพ็คเกจ --",
      travel_date: "วันที่เดินทาง",
      num_guests: "จำนวนผู้เข้าพัก",
      adults: "ผู้ใหญ่",
      adults_desc: "อายุ 12+ ปี",
      children: "เด็ก",
      children_desc: "ลด 50% (2-11 ปี)",
      infants: "ทารก",
      infants_desc: "ฟรี (อายุต่ำกว่า 2 ปี)",
      acc_class: "ระดับที่พัก",
      std_class: "มาตรฐาน",
      std_desc: "รวมอยู่ด้วย",
      deluxe_class: "ดีลักซ์",
      lux_class: "หรูหรา",
      pax: "/ท่าน",
      lead_guest: "รายละเอียดผู้เข้าพักหลัก",
      full_name: "ชื่อเต็ม",
      carbon_footprint: "คาร์บอนฟุตพริ้นท์ - ไปที่ Forest Foundation Philippines",
      carbon_desc: "การเดินทางทำให้เกิดการปล่อยก๊าซ ปริมาณที่คาดว่าจะเกิดขึ้นสำหรับ",
      carbon_desc2: "นักเดินทางคือ",
      carbon_desc3: "ช่วยเราชดเชยสิ่งนี้",
      offset_carbon: "ชดเชยคาร์บอนฟุตพริ้นท์ของฉัน",
      optional_addons: "ส่วนเสริมทางเลือก",
      transfer: "รถรับส่งสนามบิน",
      transfer_desc: "รับส่งสะดวกสบาย",
      insurance: "ประกันการเดินทาง",
      insurance_desc: "คุ้มครองเต็มรูปแบบ",
      dinner: "ดินเนอร์สุดโรแมนติก",
      dinner_desc: "ดินเนอร์ใต้แสงเทียน",
      payment_details: "รายละเอียดการชำระเงิน",
      how_paying: "เราจะจ่ายเงินอย่างไร?",
      split_1: "ฉันเท่านั้น (จ่ายเต็มจำนวน)",
      split_ways: "แบ่งปันให้",
      split_ways2: "คน",
      invoice_emails: "อีเมลสำหรับใบแจ้งหนี้:",
      lead_email: "อีเมลผู้จองหลัก",
      friend_email: "อีเมลของเพื่อน",
      friend_email2: "",
      each_pays: "แต่ละคนจะจ่าย",
      invoices_tied: "ใบแจ้งหนี้จะเชื่อมโยงกับอีเมลเหล่านี้",
      payment_method: "วิธีการชำระเงิน",
      select_summary: "เลือกแพ็คเกจเพื่อดูสรุป",
      split: "แบ่ง",
      ways: "คน",
      per_person2: "/คน",
      secure_payment: "การชำระเงินที่ปลอดภัย",
      processing: "กำลังประมวลผล...",
      region: "ภูมิภาค",
      all_regions: "ทุกภูมิภาค",
      accommodation: "ที่พัก",
      all_acc: "ที่พักทั้งหมด",
      keyword_search: "ค้นหาคำสำคัญ",
      search_placeholder: "พิมพ์เพื่อค้นหา...",
      filters: "ตัวกรอง",
      clear_all: "ล้างทั้งหมด",
      explore_regions: "สำรวจภูมิภาค",
      major_regions: "6 ภูมิภาคหลัก",
      view_acc: "ดูที่พัก",
      search_results: "ผลการค้นหา",
      dest_found: "พบจุดหมายปลายทาง",
      no_match: "ไม่พบที่พักที่ตรงกัน",
      no_match_desc: "ลองนำตัวกรองบางตัวออก",
      back_places: "← กลับไปที่สถานที่ทั้งหมด",
      pay_offers: "การชำระเงินและข้อเสนอ",
      facilities: "สิ่งอำนวยความสะดวก",
      details: "รายละเอียด",
      bed_type: "ประเภทเตียง",
      num_bedrooms: "ห้องนอน",
      beach_access: "ทางลงหาด",
      hiking: "การเดินป่า",
      distance: "ระยะทาง",
      family: "ครอบครัว",
      view_360: "มุมมอง 360°",
      full_screen: "เต็มหน้าจอ",
      starting_at: "เริ่มต้นที่",
      per_night: "/ คืน",
      weather: "สภาพอากาศ",
      location: "สถานที่",
      select_region_first: "เลือกภูมิภาคก่อน",
      all_locations: "สถานที่ทั้งหมด",
      explore_by_region: "สำรวจตามภูมิภาค",
      regions_count: "ภูมิภาค",
      destinations: "จุดหมายปลายทาง",
      locations_count: "สถานที่",
      gallery: "แกลเลอรี",
      photos_count: "รูปภาพ",
      back_to_regions: "กลับไปที่ภูมิภาคทั้งหมด",
      back_to: "กลับไปที่",
      promo_banner: "พิเศษหน้ามรสุม: ลด 30% สำหรับแพ็คเกจปาลาวันทั้งหมด!",
      stats_clients: "ลูกค้าที่พึงพอใจ",
      stats_tours: "ทัวร์ที่จัดขึ้น",
      stats_dest: "จุดหมายปลายทาง",
      
      // ⚡ THAI NEW KEYS
      island_subtitle: "การค้นพบ",
      island_title: "นักผจญภัยข้ามเกาะ",
      island_desc1: "บางครั้งการผจญภัยที่ดีที่สุดเริ่มต้นในจุดที่มหาสมุทรบรรจบกับชายฝั่ง ก้าวขึ้นเรือบังกาแบบดั้งเดิม สัมผัสลมทะเล และเดินทางข้ามเกาะที่บริสุทธิ์ซึ่งรอการค้นพบ",
      island_desc2: "ล่องเรือผ่านหน้าผาหินปูนสูงตระหง่านไปยังทะเลสาบที่ซ่อนอยู่ซึ่งมีน้ำสีเทอร์ควอยซ์ใส ทอดสมอที่ชายหาดทรายขาวอันเงียบสงบและดำดิ่งสู่เขตอนุรักษ์ทางทะเลที่มีชีวิตชีวา",
      island_btn: "สำรวจทัวร์เกาะ",
      
      regional: "ภูมิภาค",
      pop_dest_desc: "ค้นพบภูมิภาคและสถานที่สำคัญที่ฟิลิปปินส์มีให้",
      view_all_dest: "ดูจุดหมายปลายทางทั้งหมด",
      relaxation: "การพักผ่อน",
      bask_sun: "อาบแดด",
      sun_desc1: "สัมผัสความอบอุ่นของแสงแดดเขตร้อนบนผิวของคุณในขณะที่คุณพักผ่อนบนชายหาดทรายขาวที่สวยงามที่สุดแห่งหนึ่ง",
      sun_desc2: "ปล่อยให้จังหวะที่นุ่มนวลของคลื่นชะล้างความกังวลของคุณ ไม่ว่าคุณจะดื่มมะพร้าวสดใต้ต้นปาล์มหรือเดินลุยน้ำทะเลใส",
      book_beach: "จองรีสอร์ทริมหาด",
      packages: "แพ็คเกจ",
      explore_all_tours: "สำรวจทัวร์ทั้งหมด",
      testimonials: "คำวิจารณ์",
      what_clients_say: "ลูกค้าของเราพูดว่าอย่างไร",
      quote1: "\"PhilGood Travels ทำให้ทริปเอลนิโดของเราน่าจดจำอย่างแน่นอน!\"",
      quote2: "\"ทัวร์ช็อคโกแลตฮิลส์นั้นน่าทึ่งมาก! ทุกอย่างจัดได้ดีมาก\"",
      quote3: "\"ในฐานะผู้มาเยือนฟิลิปปินส์ครั้งแรก ฉันประทับใจในบริการมาก ขอแนะนำอย่างยิ่ง!\"",
      ready_adventure: "พร้อมสำหรับการผจญภัยครั้งต่อไปหรือยัง?",
      ready_desc: "จองวันหยุดพักผ่อนในฝันที่ฟิลิปปินส์ของคุณวันนี้และสร้างความทรงจำ",
      start_journey: "เริ่มต้นการเดินทางของคุณ",
      underwater: "ใต้น้ำ",
      next_dive: "พร้อมสำหรับการดำน้ำครั้งต่อไปหรือยัง?",
      dive_desc1: "ดำดิ่งลงสู่สีน้ำเงินลึก ค้นพบแนวปะการังที่มีชีวิตชีวา ว่ายน้ำไปกับเต่าทะเลที่สง่างาม",
      dive_desc2: "นอกเหนือจากสวนปะการังคือโลกที่หยุดนิ่ง นำทางผ่านซากเรือที่น่าขนลุก",
      view_diving: "ดูแพ็คเกจดำน้ำ"
    },
    ms: {
      nav_home: "Utama",
      nav_dest: "Destinasi",
      nav_tours: "Lawatan Pilihan",
      nav_gallery: "Galeri",
      nav_connect: "Hubungi",
      nav_book: "TEMPAH SEKARANG",
      book_now: "Tempah Sekarang",
      view_details: "Lihat Butiran",
      select: "Pilih",
      per_person: "seorang",
      total: "Jumlah",
      confirm: "Sahkan Tempahan",
      pop_dest: "Destinasi Paling Popular",
      top_pkg: "Pakej Terbaik Untuk Anda",
      calc_price: "KIRA JUMLAH HARGA",
      hero_island: "PULAU PARADISE",
      hero_adv: "PENGEMBARAAN MENANTI",
      hero_trail: "CARI LALUAN ANDA",
      dest_title: "CARI TEMPAT ANDA",
      tours_title: "PAKEJ LAWATAN",
      gal_title: "PERJALANAN VISUAL",
      conn_title: "HUBUNGI KAMI",
      price_summary: "Ringkasan Harga",
      contact_info: "Maklumat Hubungan",
      contact_desc: "Pakar pelancongan kami sedia membantu anda. Hubungi kami melalui e-mel, telefon, atau lawati pejabat kami.",
      head_office: "Ibu Pejabat",
      phone: "Nombor Telefon",
      email_addr: "Alamat E-mel",
      send_msg: "Hantar Mesej",
      your_name: "Nama Anda",
      your_email: "E-mel Anda",
      subject: "Subjek",
      message: "Mesej",
      placeholder_help: "Bagaimana kami boleh membantu?",
      placeholder_msg: "Tulis mesej anda di sini...",
      btn_send: "HANTAR MESEJ",
      booking_title: "Sahkan Tempat Anda",
      booking_desc: "Lengkapkan tempahan anda",
      trip_details: "Butiran Perjalanan",
      dest_pkg: "Destinasi / Pakej",
      select_pkg: "-- Pilih Pakej --",
      travel_date: "Tarikh Perjalanan",
      num_guests: "Bilangan Tetamu",
      adults: "Dewasa",
      adults_desc: "12+ tahun",
      children: "Kanak-kanak",
      children_desc: "Diskaun 50% (2-11 thn)",
      infants: "Bayi",
      infants_desc: "Percuma (Bawah 2)",
      acc_class: "Kelas Penginapan",
      std_class: "Standard",
      std_desc: "Termasuk",
      deluxe_class: "Deluxe",
      lux_class: "Mewah",
      pax: "/pax",
      lead_guest: "Butiran Tetamu Utama",
      full_name: "Nama Penuh",
      carbon_footprint: "Jejak Karbon - pergi ke Forest Foundation Philippines Karbon",
      carbon_desc: "Perjalanan menghasilkan pelepasan. Anggaran jejak untuk",
      carbon_desc2: "pengembara ialah",
      carbon_desc3: "Bantu kami mengimbangi ini.",
      offset_carbon: "Imbangi Jejak Karbon Saya",
      optional_addons: "Tambahan Pilihan",
      transfer: "Pemindahan Lapangan Terbang",
      transfer_desc: "Pengambilan tanpa masalah.",
      insurance: "Insurans Perjalanan",
      insurance_desc: "Perlindungan penuh.",
      dinner: "Makan Malam Romantik",
      dinner_desc: "Makan malam cahaya lilin.",
      payment_details: "Butiran Pembayaran",
      how_paying: "Bagaimana kita membayar?",
      split_1: "Hanya saya (Bayar penuh)",
      split_ways: "Bahagikan kepada",
      split_ways2: "orang",
      invoice_emails: "E-mel untuk Invois:",
      lead_email: "E-mel Pengepah Utama",
      friend_email: "E-mel Rakan",
      friend_email2: "",
      each_pays: "Setiap orang akan membayar",
      invoices_tied: "Invois akan diikat pada e-mel ini.",
      payment_method: "Kaedah Pembayaran",
      select_summary: "Pilih pakej untuk melihat ringkasan",
      split: "Bahagi",
      ways: "orang",
      per_person2: "/orang",
      secure_payment: "Pembayaran Selamat",
      processing: "Memproses...",
      region: "Wilayah",
      all_regions: "Semua Wilayah",
      accommodation: "Penginapan",
      all_acc: "Semua Penginapan",
      keyword_search: "Carian Kata Kunci",
      search_placeholder: "Taip untuk mencari...",
      filters: "Penapis",
      clear_all: "Kosongkan Semua",
      explore_regions: "Terokai Wilayah",
      major_regions: "6 Wilayah Utama",
      view_acc: "Lihat Penginapan",
      search_results: "Hasil Carian",
      dest_found: "destinasi ditemui",
      no_match: "Tiada penginapan sepadan",
      no_match_desc: "Cuba buang beberapa penapis.",
      back_places: "← Kembali ke Semua Tempat",
      pay_offers: "PEMBAYARAN & TAWARAN",
      facilities: "KEMUDAHAN",
      details: "BUTIRAN",
      bed_type: "Jenis Katil",
      num_bedrooms: "Bilik Tidur",
      beach_access: "Akses Pantai",
      hiking: "Mendaki",
      distance: "Jarak",
      family: "Keluarga",
      view_360: "PANDANGAN 360°",
      full_screen: "Skrin Penuh",
      starting_at: "Bermula dari",
      per_night: "/ malam",
      weather: "Cuaca",
      location: "Lokasi",
      select_region_first: "Pilih Wilayah dahulu",
      all_locations: "Semua Lokasi",
      explore_by_region: "Teroka mengikut Wilayah",
      regions_count: "Wilayah",
      destinations: "Destinasi",
      locations_count: "Lokasi",
      gallery: "Galeri",
      photos_count: "Foto",
      back_to_regions: "Kembali ke Semua Wilayah",
      back_to: "Kembali ke",
      promo_banner: "ISTIMEWA MONSUN: DISKAUN 30% untuk semua pakej Palawan!",
      stats_clients: "PELANGGAN BERPUAS HATI",
      stats_tours: "LAWATAN DIANJURKAN",
      stats_dest: "DESTINASI",
      
      // ⚡ MALAY NEW KEYS
      island_subtitle: "PENEMUAN",
      island_title: "Penjelajah Pulau",
      island_desc1: "Kadang-kadang pengembaraan terbaik bermula di mana lautan bertemu pantai. Naik bangka tradisional, rasakan bayu laut, dan lompat antara pulau-pulau dara yang menunggu untuk ditemui.",
      island_desc2: "Belayar melepasi tebing batu kapur yang menjulang tinggi ke lagun tersembunyi dengan air biru pirus yang jernih. Jatuhkan sauh di pantai pasir putih yang terpencil dan selami tempat perlindungan marin yang meriah.",
      island_btn: "Teroka Lawatan Pulau",
      
      regional: "Serantau",
      pop_dest_desc: "Temui wilayah dan mercu tanda utama yang ditawarkan oleh Filipina.",
      view_all_dest: "Lihat Semua Destinasi",
      relaxation: "RELAKSASI",
      bask_sun: "Berjemur di Bawah Matahari",
      sun_desc1: "Rasakan kehangatan matahari tropika pada kulit anda sambil bersantai di beberapa pantai pasir putih yang paling indah di dunia.",
      sun_desc2: "Biar rentak ombak menghilangkan kerisauan anda. Sama ada anda menghirup kelapa segar di bawah pokok palma atau meredah air yang jernih.",
      book_beach: "Tempah Resort Pantai",
      packages: "Pakej",
      explore_all_tours: "Teroka Semua Lawatan",
      testimonials: "Testimoni",
      what_clients_say: "Apa Kata Pelanggan Kami",
      quote1: "\"PhilGood Travels menjadikan percutian El Nido kami sangat tidak dapat dilupakan!\"",
      quote2: "\"Lawatan Chocolate Hills sangat menakjubkan! Semuanya teratur dengan baik.\"",
      quote3: "\"Sebagai pelawat kali pertama, saya kagum dengan perkhidmatan. Sangat disyorkan!\"",
      ready_adventure: "Bersedia untuk pengembaraan seterusnya?",
      ready_desc: "Tempah percutian impian anda di Filipina hari ini dan cipta kenangan.",
      start_journey: "MULA PERJALANAN ANDA",
      underwater: "BAWAH AIR",
      next_dive: "Bersedia untuk selaman seterusnya?",
      dive_desc1: "Turun ke biru yang dalam. Temui terumbu karang yang meriah, berenang bersama penyu laut yang megah.",
      dive_desc2: "Di sebalik taman karang terdapat dunia yang membeku dalam masa. Navigasi melalui bangkai kapal yang menakutkan.",
      view_diving: "Lihat Pakej Menyelam"
    },
    id: {
      nav_home: "Beranda",
      nav_dest: "Destinasi",
      nav_tours: "Tur Pilihan",
      nav_gallery: "Galeri",
      nav_connect: "Kontak",
      nav_book: "PESAN SEKARANG",
      book_now: "Pesan Sekarang",
      view_details: "Lihat Detail",
      select: "Pilih",
      per_person: "per orang",
      total: "Total",
      confirm: "Konfirmasi Pemesanan",
      pop_dest: "Destinasi Paling Populer",
      top_pkg: "Paket Terbaik Untuk Anda",
      calc_price: "HITUNG TOTAL HARGA",
      hero_island: "PULAU SURGA",
      hero_adv: "PETUALANGAN MENANTI",
      hero_trail: "TEMUKAN JALUR ANDA",
      dest_title: "TEMUKAN TEMPAT ANDA",
      tours_title: "PAKET TUR",
      gal_title: "PERJALANAN VISUAL",
      conn_title: "HUBUNGI KAMI",
      price_summary: "Ringkasan Harga",
      contact_info: "Informasi Kontak",
      contact_desc: "Pakar perjalanan kami siap membantu Anda. Hubungi kami melalui email, telepon, atau kunjungi kantor kami.",
      head_office: "Kantor Pusat",
      phone: "Nombor Telepon",
      email_addr: "Alamat Email",
      send_msg: "Kirim Pesan",
      your_name: "Nama Anda",
      your_email: "Email Anda",
      subject: "Subjek",
      message: "Pesan",
      placeholder_help: "Bagaimana kami bisa membantu?",
      placeholder_msg: "Tulis pesan Anda di sini...",
      btn_send: "KIRIM PESAN",
      booking_title: "Amankan Tempat Anda",
      booking_desc: "Selesaikan pemesanan Anda",
      trip_details: "Detail Perjalanan",
      dest_pkg: "Destinasi / Paket",
      select_pkg: "-- Pilih Paket --",
      travel_date: "Tanggal Perjalanan",
      num_guests: "Jumlah Tamu",
      adults: "Dewasa",
      adults_desc: "12+ tahun",
      children: "Anak-anak",
      children_desc: "Diskon 50% (2-11 thn)",
      infants: "Bayi",
      infants_desc: "Gratis (Di bawah 2)",
      acc_class: "Kelas Akomodasi",
      std_class: "Standar",
      std_desc: "Termasuk",
      deluxe_class: "Deluxe",
      lux_class: "Mewah",
      pax: "/pax",
      lead_guest: "Detail Tamu Utama",
      full_name: "Nama Lengkap",
      carbon_footprint: "Jejak Karbon - pergi ke Forest Foundation Philippines",
      carbon_desc: "Perjalanan menghasilkan emisi. Perkiraan jejak untuk",
      carbon_desc2: "wisatawan adalah",
      carbon_desc3: "Bantu kami mengimbanginya.",
      offset_carbon: "Imbangi Jejak Karbon Saya",
      optional_addons: "Tambahan Opsional",
      transfer: "Transfer Bandara",
      transfer_desc: "Penjemputan tanpa repot.",
      insurance: "Asuransi Perjalanan",
      insurance_desc: "Cakupan penuh.",
      dinner: "Makan Malam Romantis",
      dinner_desc: "Makan malam dengan cahaya lilin.",
      payment_details: "Detail Pembayaran",
      how_paying: "Bagaimana kita membayar?",
      split_1: "Hanya saya (Bayar penuh)",
      split_ways: "Bagi",
      split_ways2: "orang",
      invoice_emails: "Email untuk Faktur:",
      lead_email: "Email Pemesan Utama",
      friend_email: "Email Teman",
      friend_email2: "",
      each_pays: "Setiap orang akan membayar",
      invoices_tied: "Faktur akan dikaitkan dengan email ini.",
      payment_method: "Metode Pembayaran",
      select_summary: "Pilih paket untuk melihat ringkasan",
      split: "Bagi",
      ways: "orang",
      per_person2: "/orang",
      secure_payment: "Pembayaran Aman",
      processing: "Memproses...",
      region: "Wilayah",
      all_regions: "Semua Wilayah",
      accommodation: "Akomodasi",
      all_acc: "Semua Akomodasi",
      keyword_search: "Pencarian",
      search_placeholder: "Ketik untuk mencari...",
      filters: "Filter",
      clear_all: "Hapus Semua",
      explore_regions: "Jelajahi Wilayah",
      major_regions: "6 Wilayah Utama",
      view_acc: "Lihat Akomodasi",
      search_results: "Hasil Pencarian",
      dest_found: "destinasi ditemukan",
      no_match: "Tidak ada akomodasi yang cocok",
      no_match_desc: "Cobalah menghapus beberapa filter.",
      back_places: "← Kembali ke Semua Tempat",
      pay_offers: "PEMBAYARAN & PENAWARAN",
      facilities: "FASILITAS",
      details: "DETAIL",
      bed_type: "Tipe Tempat Tidur",
      num_bedrooms: "Kamar Tidur",
      beach_access: "Akses Pantai",
      hiking: "Mendaki",
      distance: "Jarak",
      family: "Keluarga",
      view_360: "TAMPILAN 360°",
      full_screen: "Layar Penuh",
      starting_at: "Mulai dari",
      per_night: "/ malam",
      weather: "Cuaca",
      location: "Lokasi",
      select_region_first: "Pilih Wilayah terlebih dahulu",
      all_locations: "Semua Lokasi",
      explore_by_region: "Jelajahi Berdasarkan Wilayah",
      regions_count: "Wilayah",
      destinations: "Destinasi",
      locations_count: "Lokasi",
      gallery: "Galeri",
      photos_count: "Foto",
      back_to_regions: "Kembali ke Semua Wilayah",
      back_to: "Kembali ke",
      promo_banner: "SPESIAL MONSUN: DISKON 30% untuk semua paket Palawan!",
      stats_clients: "KLIEN PUAS",
      stats_tours: "TUR DISELENGGARAKAN",
      stats_dest: "DESTINASI",
      
      // ⚡ INDONESIAN NEW KEYS
      island_subtitle: "PENEMUAN",
      island_title: "Penjelajah Pulau",
      island_desc1: "Terkadang petualangan terbaik dimulai di mana lautan bertemu dengan pantai. Naiklah bangka tradisional, rasakan angin laut, dan jelajahi pulau-pulau perawan yang menunggu untuk ditemukan.",
      island_desc2: "Berlayar melewati tebing batu kapur yang menjulang tinggi menuju laguna tersembunyi dengan air pirus sebening kristal. Jatuhkan jangkar di pantai pasir putih terpencil dan selami cagar alam laut yang semarak.",
      island_btn: "Jelajahi Tur Pulau",
      
      regional: "Regional",
      pop_dest_desc: "Temukan wilayah dan landmark utama yang ditawarkan Filipina.",
      view_all_dest: "Lihat Semua Destinasi",
      relaxation: "RELAKSASI",
      bask_sun: "Berjemur di Bawah Sinar Matahari",
      sun_desc1: "Rasakan hangatnya sinar matahari tropis di kulit Anda sambil bersantai di beberapa pantai pasir putih terindah.",
      sun_desc2: "Biarkan ritme ombak yang lembut menyapu kekhawatiran Anda. Baik Anda menyesap kelapa segar atau mengarungi perairan jernih.",
      book_beach: "Pesan Resor Pantai",
      packages: "Paket",
      explore_all_tours: "Jelajahi Semua Tur",
      testimonials: "Testimoni",
      what_clients_say: "Apa Kata Klien Kami",
      quote1: "\"PhilGood Travels membuat perjalanan El Nido kami benar-benar tak terlupakan!\"",
      quote2: "\"Tur Chocolate Hills sangat menakjubkan! Semuanya terorganisir dengan baik.\"",
      quote3: "\"Sebagai pengunjung pertama kali, saya terkesan dengan layanannya. Sangat direkomendasikan!\"",
      ready_adventure: "Siap untuk Petualangan Anda Berikutnya?",
      ready_desc: "Pesan liburan impian Anda di Filipina hari ini dan ciptakan kenangan.",
      start_journey: "MULAI PERJALANAN ANDA",
      underwater: "BAWAH AIR",
      next_dive: "Siap untuk penyelaman Anda berikutnya?",
      dive_desc1: "Turun ke biru tua. Temukan terumbu karang yang semarak, berenang bersama penyu laut yang megah.",
      dive_desc2: "Di luar taman karang terdapat dunia yang membeku dalam waktu. Navigasi melalui bangkai kapal yang menghantui.",
      view_diving: "Lihat Paket Menyelam"
    }
  };

  const t = (key, defaultText) => translations[language]?.[key] || translations['en'][key] || defaultText;

  const formatPrice = (phpAmount) => {
    const converted = phpAmount * exchangeRates[currency];
    const currData = availableCurrencies.find(c => c.code === currency);
    return `${currData ? currData.symbol : ''}${converted.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
  };

  return (
    <PreferencesContext.Provider value={{ 
        language, setLanguage, currency, setCurrency, 
        theme, setTheme, 
        t, formatPrice, availableCurrencies, availableLanguages 
    }}>
      {children}
    </PreferencesContext.Provider>
  );
};